version: 2
updates:
  - package-ecosystem: "helm"
    directories:
      - "./charts/htp-bindplane"
    schedule:
      interval: "daily"
    labels:
      - "type: dependencies"
    commit-message:
      prefix: "maint"
      include: "scope"
