apiVersion: v2
name: refinery
description: Chart to deploy Honeycomb Refinery
type: application
version: 2.11.4
appVersion: 2.8.2
keywords:
  - refinery
  - honeycomb
  - observability
  - sampling
  - tracing
home: https://honeycomb.io
sources:
  - https://github.com/honeycombio/refinery
icon: https://www.honeycomb.io/wp-content/themes/honeycomb/assets/img/logo.svg
maintainers:
  - name: Honeycomb
    email: collection-team@honeycomb.io
