apiVersion: v2
name: refinery
description: Chart to deploy Honeycomb Refinery
type: application
version: 3.0.4
appVersion: 3.0.1
keywords:
  - refinery
  - honeycomb
  - observability
  - sampling
  - tracing
home: https://honeycomb.io
sources:
  - https://github.com/honeycombio/refinery
icon: https://raw.githubusercontent.com/honeycombio/helm-charts/main/hny_logo.svg
maintainers:
  - name: Honeycomb
    email: collection-team@honeycomb.io
