apiVersion: v2
name: htp-builder
description: Chart to deploy Honeycomb Telemetry Pipeline Builder
type: application
version: 0.2.0
appVersion: 0.1.1
keywords:
  - refinery
  - open-telemetry
  - honeycomb
  - observability
  - sampling
  - tracing
  - collector
  - htp
home: https://honeycomb.io
sources:
  - https://github.com/honeycombio/refinery
  - https://github.com/honeycombio/supervised-collector
  - https://github.com/open-telemetry/opentelemetry-collector-releases
icon: https://www.honeycomb.io/wp-content/themes/honeycomb/assets/img/logo.svg
maintainers:
  - name: Honeycomb
    email: pipeline-team@honeycomb.io
