apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "refinery.fullname" . }}-config
  labels:
  {{- include "refinery.labels" . | nindent 4 }}
data:
  config.toml: |
{{ tpl (.Files.Get "config.toml") . | indent 6 }}
