
honeycomb:
  # Specify Auth Token used for Secure Tenancy
  authToken: YOUR_AUTH_TOKEN
  # Specify host URL to send Honeycomb format events to
  apiHost: https://api.honeycomb.io

  uiBaseUrl: https://ui.honeycomb.io
  
  maxIdleConnsPerHost: 100
  hsts:
    enabled: false
    maxAge: 31536000

  # Transformer to use.  Valid values are `aes256siv` or `sha256hmac`
  transformer: aes256siv
  

image:
  # this must be provided
  repository: 
  tag:
  pullPolicy: IfNotPresent


replicaCount: 2


# Secure Tenancy self-metrics.
metrics:
  # leave API key blank to disable self-metrics
  apiKey:
  dataset: secure-tenancy
  apiHost: https://api.honeycomb.io


mysql:
  # to install the mysql chart (mariadb from bitnami) set this to true
  # if false, you must specify a value for existingHost
  enabled: true
  # if mysql.enabled is false this needs to be specified when the name of the host
  # when specified mysql will not be installed and the specified host:port will be used instead
  # this takes not effect if mysql.enabled is true
  # existingHost: 

  # Use TLS when communicating with MySQL
  tls: false
  # Max open connections
  maxopenconns: 100

  db:
    # MySQL user
    user: hny-secure-tenancy
    # MySQL password
    password: db_password
    # MySQL database
    name: hny-secure-tenancy
  
  # if mysql.enabled is true, ths is the root password used
  rootUser:
    password: root_password
  # if mysql.enabled is true, this is the replication password, can be disabled with mysql.replication.enabled set to false
  replication:
    password: replication_password

  # disable tests by default 
  tests:
    enabled: false

       
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  annotations: {}
  type: ClusterIP
  port: 80
  grpcPort: 4317
  # If using a LoadBalancer service, you may also want to specify the IP to use
  # ip: 

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: secure-tenancy.local
      paths: []
  tls: []
  #  - secretName: secure-tenancy-tls
  #    hosts:
  #      - secure-tenancy.local

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

podAnnotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
