apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "secure-tenancy.fullname" . }}
  labels:
  {{- include "secure-tenancy.labels" . | nindent 4 }}
data:
  hnyconfig.yaml: |
    ui_base_url: {{ .Values.honeycomb.uiBaseUrl | quote }}
    api_base_url: {{ .Values.honeycomb.apiHost | quote }}
    libhoney_dataset: {{ .Values.metrics.dataset | quote }}
    libhoney_api_url: {{ .Values.metrics.apiHost | quote }}
    http_strict_transport_security_enabled: {{ .Values.honeycomb.hsts.enabled }}
    http_strict_transport_security_max_age: {{ .Values.honeycomb.hsts.maxAge }}
    max_idle_conns_per_host: {{ .Values.honeycomb.maxIdleConnsPerHost }}
    grpc_base_url: 0.0.0.0:8081
  mysqlconfig.yaml: |
    host: "{{ include "db.fullhost" . }}"
    database: {{ .Values.mysql.db.name | quote }}
    tls: {{ .Values.mysql.tls }}
    maxopenconns: {{ .Values.mysql.maxopenconns }}
