apiVersion: v2
name: honeycomb
description: Honeycomb Kubernetes Agent
version: 1.9.1
appVersion: 2.7.3
keywords:
  - observability
  - tracing
  - logs
  - events
home: https://honeycomb.io
sources:
  - https://github.com/honeycombio/honeycomb-kubernetes-agent
icon: https://www.honeycomb.io/wp-content/themes/honeycomb/assets/img/logo.svg
maintainers:
  - name: Honeycomb
    email: collection-team@honeycomb.io
