apiVersion: v2
name: honeycomb
description: Honeycomb Kubernetes Agent
version: 1.9.3
appVersion: 2.7.4
keywords:
  - observability
  - tracing
  - logs
  - events
home: https://honeycomb.io
sources:
  - https://github.com/honeycombio/honeycomb-kubernetes-agent
icon: https://raw.githubusercontent.com/honeycombio/helm-charts/main/hny_logo.svg
maintainers:
  - name: Honeycomb
    email: collection-team@honeycomb.io
