apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  labels:
  {{- include "opentelemetry-collector.labels" . | nindent 4 }}
data:
  opentelemetry-collector-config: |
    receivers:
    {{- if .Values.config.receivers }}
    {{- toYaml .Values.config.receivers | nindent 6 }}
    {{- end }}

    processors:
    {{- if .Values.config.processors }}
    {{- toYaml .Values.config.processors | nindent 6 }}
    {{- end }}

    exporters:
      honeycomb:
        api_key: ${HONEYCOMB_API_KEY}
        api_url: {{ .Values.honeycomb.apiHost }}
        dataset: {{ .Values.honeycomb.dataset }}
    {{- if .Values.config.exporters }}
    {{- toYaml .Values.config.exporters | nindent 6 }}
    {{- end }}

    extensions:
    {{- if .Values.config.extensions }}
    {{- toYaml .Values.config.extensions | nindent 6 }}
    {{- end }}

    service:
    {{- if .Values.config.service }}
    {{- toYaml .Values.config.service | nindent 6 }}
    {{- end }}


