apiVersion: v1
kind: Service
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "opentelemetry-collector.selectorLabels" . | nindent 4 }}
  ports:
    - name: otlp # Default endpoint for otlp receiver.
      port: 55680
      protocol: TCP
      targetPort: 55680
    - name: jaeger-grpc # Default endpoing for Jaeger gRPC receiver
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: jaeger-http # Default endpoint for Jaeger HTTP receiver.
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: zipkin # Default endpoint for Zipkin receiver.
      port: 9411
      protocol: TCP
      targetPort: 9411
    - name: metrics # Default endpoint for querying metrics.
      port: 8888
      protocol: TCP
      targetPort: 8888
